apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "sonarqube-api.fullname" . }}-gateway
  namespace: {{ .Values.qubeapisDep.namespace }}
  labels:
  {{- include "sonarqube-api.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - sonar.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
