apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "sonarqube-api.fullname" . }}-virtualservice
  namespace: {{ .Values.qubeapisDep.namespace }}
  labels:
  {{- include "sonarqube-api.labels" . | nindent 4 }}
spec:
  gateways:
  - sonar-gateway
  hosts:
  - sonar.example.com
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      authority: sonarqubeapis-service.platformenv.svc.cluster.local:8082
      uri: /
    route:
    - destination:
        host: sonarqubeapis-service.platformenv.svc.cluster.local
        port:
          number: 8082
