apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline-api.fullname" . }}-apis-service
  namespace: {{ .Values.apisDep.namespace }}
  labels:
  {{- include "pipeline-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apisService.type }}
  selector:
    app: pipelineapis
  {{- include "pipeline-api.selectorLabels" . | nindent 4 }}
  ports:
        {{- .Values.apisService.ports | toYaml | nindent 2 -}}
