apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "pipeline-api.fullname" . }}-virtualservice
  namespace: {{ .Values.apisDep.namespace }}
  labels:
  {{- include "pipeline-api.labels" . | nindent 4 }}
spec:
  gateways:
  - pipeline-gateway
  hosts:
  - pipeline.example.com
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      authority: pipelineapis-service.platformenv.svc.cluster.local:8080
      uri: /
    route:
    - destination:
        host: pipelineapis-service.platformenv.svc.cluster.local
        port:
          number: 8080
