apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-api.fullname" . }}-apis-service
  namespace: {{ .Values.apisDep.namespace }}
  labels:
  {{- include "nexus-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apisService.type }}
  selector:
    app: nexusapis
  {{- include "nexus-api.selectorLabels" . | nindent 4 }}
  ports:
        {{- .Values.apisService.ports | toYaml | nindent 2 -}}
