apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}-XYZ-grafana
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.xYZGrafana.type }}
  selector:
    app: XYZ-grafana
  {{- include "grafana.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.xYZGrafana.ports | toYaml | nindent 2 -}}