apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "secret-management.fullname" . }}-gateway
  namespace: {{ .Values.application.namespace }}
  labels:
  {{- include "secret-management.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - vault.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
