apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnerability-scanning-ms.fullname" . }}-service
  namespace: {{ .Values.scanning.namespace }}
  labels:
  {{- include "vulnerability-scanning-ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: scanning
  {{- include "vulnerability-scanning-ms.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}
