deployment:
  replicas: 1
  namespace: NAMESPACE
  templateService:
    env:
      dbHost: 10.63.35.218
      dbPass: Admin@123
      dbUser: admin
      port: "32001"
      sandboxEnv: http://10.63.35.134:8000/
      username: ayush
    image:
      repository: 10.63.33.77:32003
      imageName: cluster-provisioning
      tag: 6
    imagePullPolicy: Always
    imagePullSecrets: SECRET1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: ClusterIP
