apiVersion: v1
kind: Service
metadata:
  name: {{ include "template-service.fullname" . }}-service
  namespace: {{ .Values.deployment.namespace }}
  labels:
  {{- include "template-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: template
  {{- include "template-service.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}
