apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandbox-ms.fullname" . }}-service
  namespace: {{ .Values.deployment.namespace }}
  labels:
  {{- include "sandbox-ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sandbox
  {{- include "sandbox-ms.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}
