apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "efk.fullname" . }}-efk-gateway
  namespace: {{ .Values.commonNamespace.namespace }}
  labels:
  {{- include "efk.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - efk.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
