apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "efk.fullname" . }}-fluentd-config
  namespace: {{ .Values.commonNamespace.namespace }}
  labels:
  {{- include "efk.labels" . | nindent 4 }}
data:
  fluent.conf: {{ .Values.fluentdConfig.fluentConf | toYaml | indent 1 }}
