apiVersion: v1
kind: Service
metadata:
  name: {{ include "efk.fullname" . }}-kibana
  namespace: {{ .Values.commonNamespace.namespace }}
  labels:
  {{- include "efk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kibana.type }}
  selector:
    app: kibana
  {{- include "efk.selectorLabels" . | nindent 4 }}
  ports:
        {{- .Values.kibana.ports | toYaml | nindent 2 -}}
