apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "mychart.fullname" . }}-service
  namespace: {{ .Values.dep.namespace }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - gitlab.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
