apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "mychart.fullname" . }}-service
  namespace: {{ .Values.dep.namespace }}
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  gateways:
  - gitlab-gateway
  hosts:
  - gitlab.example.com
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      authority: gitlabapis-service.platformenv.svc.cluster.local:8081
      uri: /
    route:
    - destination:
        host: gitlabapis-service.platformenv.svc.cluster.local
        port:
          number: 8080
