apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-provisioning-ms.fullname" . }}-service
  namespace: {{ .Values.dbprovision.namespace }}
  labels:
  {{- include "db-provisioning-ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dbprovision
  {{- include "db-provisioning-ms.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}
