apisDep:
  nexus:
    imagePullPolicy: Always
    imagePullSecrets: regcred
    image:
      repository: 10.63.20.43:32003
      imageName: saidurga21/nexusapis
      tag: latest
  replicas: 1
  namespace: default
apisService:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP
kubernetesClusterDomain: cluster.local
